doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '11.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Money:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/db/mappings/Money'
                prefix: 'Money'
                alias: Money
            CobiroProduct:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/db/mappings/Cobiro/Product'
                prefix: 'Cobiro\Product\Domain'
                alias: CobiroProduct
