version: "3.5"

services:
  api-nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: dev
    image: cobiro/api-nginx:local-dev
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./docker/nginx/api-dev.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/cobiro/public:cached
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
    image: cobiro/php-fpm:local-dev
    command: ["sh", "-c", "composer install ; php-fpm"]
    restart: unless-stopped
    volumes:
      - .:/var/www/cobiro:cached
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - /var/www/cobiro/var/log
      - composer-cache:/root/.composer/
  postgres:
    image: postgres:11.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cobiro
      POSTGRES_PASSWORD: cobiro
      POSTGRES_DB: cobiro_dev
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  composer-cache:
